# Generated by Django 3.0.7 on 2020-07-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0016_auto_20200701_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='do_date',
        ),
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
